name = "betpanda-api"
main = "src/index.js"
compatibility_date = "2026-01-15"
compatibility_flags = ["nodejs_compat"]
[vars]
MONGODB_DATABASE = "Betpanda"
MONGODB_COLLECTION = "platform_stats"
[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1